apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-note-api-deployment
  labels:
    app: secret-note-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-note-api
  template:
    metadata:
      labels:
        app: secret-note-api
    spec:
      containers:
      - name: secret-note-api
        image: 346088432684.dkr.ecr.us-east-2.amazonaws.com/secretnote:latest 
        ports:
        - containerPort: 8080