apiVersion: v1
kind: Service
metadata:
  name: secret-note-api-service
spec:
  selector:
    app: secret-note-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer