// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Post struct {
	ID            int64     `json:"id"`
	Email         string    `json:"email"`
	Title         string    `json:"title"`
	Content       string    `json:"content"`
	CreatedAt     time.Time `json:"created_at"`
	PostChangedAt time.Time `json:"post_changed_at"`
}

type User struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	TypeOfLogin string    `json:"type_of_login"`
	CreatedAt   time.Time `json:"created_at"`
}
